AWSTemplateFormatVersion: "2010-09-09"
Description: CFN Template for a Laravel Sail ECS application.

Parameters:
  AppName:
    Type: String
    Description: This is your app name.

Resources:
  # ECR Private Repository
  EcrPrivateRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref AppName
      LifecyclePolicy:
        LifecyclePolicyText: |
          {"rules":[{"rulePriority":1,"description":"Remove untagged images","selection":{"tagStatus":"untagged","countType":"imageCountMoreThan","countNumber":1},"action":{"type":"expire"}}]}

  # ECS
  # Cluster
  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub "${AppName}-cluster"
      ClusterSettings:
        - Name: containerInsights
          Value: enabled
