on:
  push:
    branches:
      - main

name: ECS Deploy

jobs:
  deploy:
    name: ECS Deploy
    runs-on: ubuntu-latest
    env:
      APP_NAME: laravel-sail-ecs
      AWS_REGION: ap-southeast-1
      IMAGE_TAG: main

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer
        run: |
          composer validate

      - name: Install dependencies
        run: |
          composer install --optimize-autoloader --prefer-dist --no-progress --no-suggest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          echo "::set-output name=username::AWS"
          echo "::set-output name=password::`aws ecr get-login-password`"

      - name: Docker build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -f docker/ecs/Dockerfile -t $ECR_REGISTRY/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }} .
          docker push $ECR_REGISTRY/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Download task def
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.APP_NAME }}-task-definition --query taskDefinition > task-definition.json

      - name: Render Amazon ECS task definition for container
        id: render-container
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.APP_NAME }}-container
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-container.outputs.task-definition }}
          service: ${{ env.APP_NAME }}-service
          cluster: ${{ env.APP_NAME }}-cluster
          wait-for-service-stability: true
